// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaveCars.Data.EntityFramework.Context;

namespace SaveCars.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220212233656_NewMigration")]
    partial class NewMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SaveCars.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Fabricator")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Fabricator_Name");

                    b.Property<string>("Information")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Vehicle_Information");

                    b.Property<string>("Model")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Vehicle_Model");

                    b.Property<decimal>("Price")
                        .HasPrecision(2)
                        .HasColumnType("numeric(2)")
                        .HasColumnName("Vehicle_Price");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("Vehicle_Plate");

                    b.Property<string>("Year")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("Vehicle_Year");

                    b.HasKey("Id")
                        .HasName("Pk_Vehicle");

                    b.HasIndex("Model")
                        .IsUnique();

                    b.HasIndex("VehiclePlate")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
